//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LOGIN
    {
        public int LOGIN_ID { get; set; }
        public int PARTNER_ID { get; set; }
        public System.Guid UUID { get; set; }
        public int LOGIN_KIND_ID { get; set; }
        public int MEDIA_KIND_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD_HASH { get; set; }
        public bool REQUIRED_CHANGE_PASSWORD { get; set; }
        public Nullable<System.DateTime> PASSWORD_CHANGED_TIME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> EMAIL_NOTIFIED_TIME { get; set; }
        public bool EMAIL_CONFIRMED { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<System.DateTime> SMS_NOTIFIED_TIME { get; set; }
        public bool SMS_CONFIRMED { get; set; }
        public string EXTERNAL_USER_UUID { get; set; }
        public Nullable<System.DateTime> EXTERNAL_NOTIFIED_TIME { get; set; }
        public bool EXTERNAL_CONFIRMED { get; set; }
        public bool TWO_FACTOR_ENABLED { get; set; }
        public Nullable<System.DateTime> LOCKOUT_END_TIME { get; set; }
        public bool LOCKOUT_ENABLED { get; set; }
        public int ACCESS_FAILED_COUNT { get; set; }
        public bool IS_ONLINE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string LANGUAGE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_TIME { get; set; }
        public Nullable<System.DateTime> LAST_LOGOFF_TIME { get; set; }
        public int CREATED_USER_ID { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public int UPDATED_USER_ID { get; set; }
        public System.DateTime UPDATED_TIME { get; set; }
    }
}
