//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MEDIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_MEDIA()
        {
            this.M_LOGIN = new HashSet<M_LOGIN>();
        }
    
        public int MEDIA_ID { get; set; }
        public string NAME { get; set; }
        public string LCL_NAME { get; set; }
        public bool IS_ACTIVE { get; set; }
        public int CREATED_USER_ID { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public int UPDATED_ID { get; set; }
        public System.DateTime UPDATED_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_LOGIN> M_LOGIN { get; set; }
    }
}
