//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER_PROFILE
    {
        public int USER_PROFILE_ID { get; set; }
        public int USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string PICTURE { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string MAIL_COUNTRY { get; set; }
        public string MAIL_PROVINCE { get; set; }
        public string MAIL_CITY { get; set; }
        public string MAIL_ADDRESS1 { get; set; }
        public string MAIL_ADDRESS2 { get; set; }
        public string MAIL_ADDRESS3 { get; set; }
        public string MAIL_ADDRESS4 { get; set; }
        public string MAIL_FULL_ADDRESS { get; set; }
        public string MAIL_PHONE_NUMBER { get; set; }
        public string MOBILE_PHONE_NUMBER { get; set; }
    
        public virtual M_USER M_USER { get; set; }
    }
}
