//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER
    {
        public int USER_ID { get; set; }
        public Nullable<int> LOGIN_ID { get; set; }
        public string ID { get; set; }
        public string TOKEN { get; set; }
        public string REFRESH_TOKEN { get; set; }
        public Nullable<System.DateTime> EXPIRES_IN { get; set; }
        public string NAME { get; set; }
        public string NICK_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PICTURE_URL { get; set; }
        public Nullable<int> LOGIN_PROVIDER { get; set; }
    }
}
